language: java
git:
  depth: 1
jdk:
  - openjdk8
dist: trusty
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  username: noufissa.bencherif@gmail.com
  password: $BLUEMIX_PASSWORD
  organization: noufissa.bencherif@gmail.com
  space: dev
  region: eu-gb
