package io.github.oliviercailloux.y2017;

/**
 * 
 * @author KAKAMA ET SAMI
 *
 */

public enum XmcdaModularTypes {

	DEFAULTX2, FUNCTION, EXPONENTIALFUNCTION, POINT2D, PIECEWISELINEARFUNCTIO, AFFINELINEARFUNCTION, KEYEDENTITY, ALTERNATIVE, 
	ALTERNATIVESET, CATEGORY, CATEGORYSET, ATTRIBUTE, ATTRIBUTESET, NOMINALTOCARDINAL, NOMINALTOCARDINALSET, MEASUREMENT, EXACTMEASUREMENT,
	BINARYMEASUREMENT, INTERVAL, GAUSSIAN, IMPRECISENOMINALMEASUREMENT, CRITERION, CRITERIONSET, DIRECTUTILITYCRITERION, 
	DIRECTUTILITYCRITERIONSET, NOMINALUTILITYCRITERION, NOMINALUTILITYCRITERIONSET, CARDINALUTILITYCRITERION, CARDINALUTILITYCRITERIONSET,
	DIRECTEDCRITERION, DIRECTEDCRITERIONSET, OUTRANKINGCRITERIONSET, VALUEDENTITY, VALUEDENTITYSET, EXACTVALUEDENTITY, EXACTVALUEDENTITYSET,
	ANYVALUEDPAIR, ANYVALUEDRELATION, BINARYVALUEDPAIR, BINARYRELATION, VALUEDPAIR, VALUEDRELATION, INTERVALVALUEDPAIR, INTERVALVALUEDRELATION,
	GAUSSIANVALUEDPAIR, GAUSSIANVALUEDRELATION, NOMINALVALUEDPAIR, NOMINALVALUEDRELATION, IMPRECISENOMINALVALUEDPAIR, IMPRECISENOMINALVALUEDRELATION;

}